import org.jooq.DSLContext
import org.jooq.Record
import org.jooq.Result
import org.jooq.SQLDialect
import org.jooq.impl.DSL

import java.sql.Connection
import java.sql.DriverManager

/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Webonise' at '15/12/16 8:38 PM' with Gradle 2.3
 *
 * @author Webonise, @date 15/12/16 8:38 PM
 */
class Library {

    public static void main(String[] args){
     /*   String userName = "user";
        String password = "password";
        String url = "jdbc:postgresql://ip:5432/dbName";*/
        DSLContext context

        try  {
            if(args.length < 5){
                throw new IllegalStateException("incorrect args")
            }
            def host =args[0]
            def port =args[1]
            def dbName = args[2]
            def userName = args[3]
            def password = args[4]
            def url = "jdbc:postgresql://$host:$port/$dbName"
            Connection conn = DriverManager.getConnection(url, userName, password);
            context = DSL.using(conn, SQLDialect.POSTGRES);

            //get list of all table
            String tableListString = context.fetch("SELECT table_name FROM information_schema.tables WHERE table_schema=\'public\';").formatCSV();
            List<String> tableList = tableListString.split("\\\n")
            tableList.remove(0)
            tableList.each { it ->

                def filenmae = "table_$it"+".csv"
                new File(filenmae).withWriter('utf-8') { writer ->
                    println("writing to file for $it")
                     writer.writeLine context.fetch("Select * from $it").formatCSV()
                }


            }


        }

        catch (Exception e) {
            e.printStackTrace();
        }
    }


}
